"""init pdffile

Revision ID: 2cfb3c8eecae
Revises: 
Create Date: 2026-03-08 12:32:16.971507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfb3c8eecae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfFile',
    sa.Column('pdfFile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pdfFile_uuid', sa.UUID(), nullable=False),
    sa.Column('pdfFile_name', sa.String(), nullable=False),
    sa.Column('pdfFile_author', sa.String(), nullable=False),
    sa.Column('pdfFile_type', sa.String(), nullable=False),
    sa.Column('pdfFile_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pdfFile_id'),
    sa.UniqueConstraint('pdfFile_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdfFile')
    # ### end Alembic commands ###
