"""add path column

Revision ID: c2f1941e95ff
Revises: 892cf85fa656
Create Date: 2026-03-08 13:48:41.134589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f1941e95ff'
down_revision: Union[str, Sequence[str], None] = '892cf85fa656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfFile', sa.Column('pdfFile_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfFile', 'pdfFile_path')
    # ### end Alembic commands ###
