"""refixer tout

Revision ID: 146edd03b26e
Revises: 84cf60e87a54
Create Date: 2026-03-14 13:51:08.957734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146edd03b26e'
down_revision: Union[str, Sequence[str], None] = '84cf60e87a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('all_telegram_kotob_fr', 'kitab_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('all_telegram_kotob_fr_kitab_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('all_telegram_kotob_fr', 'kitab_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('all_telegram_kotob_fr_kitab_id_seq'::regclass)"))
    # ### end Alembic commands ###
