"""Add Telegram Tables

Revision ID: 37cc54733b8a
Revises: 
Create Date: 2026-03-12 14:57:27.361241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc54733b8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_telegram_maktaba_ar',
    sa.Column('maktaba_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maktaba_uuid', sa.UUID(), nullable=False),
    sa.Column('maktaba_name', sa.String(), nullable=False),
    sa.Column('maktaba_link', sa.String(), nullable=False),
    sa.Column('maktaba_info', sa.String(), nullable=True),
    sa.Column('maktaba_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('maktaba_id'),
    sa.UniqueConstraint('maktaba_link'),
    sa.UniqueConstraint('maktaba_uuid')
    )
    op.create_table('all_telegram_maktaba_fr',
    sa.Column('maktaba_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maktaba_uuid', sa.UUID(), nullable=False),
    sa.Column('maktaba_name', sa.String(), nullable=False),
    sa.Column('maktaba_link', sa.String(), nullable=False),
    sa.Column('maktaba_info', sa.String(), nullable=True),
    sa.Column('maktaba_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('maktaba_id'),
    sa.UniqueConstraint('maktaba_link'),
    sa.UniqueConstraint('maktaba_uuid')
    )
    op.create_table('all_telegram_kotob_ar',
    sa.Column('kitab_id', sa.BigInteger(), nullable=False),
    sa.Column('kitab_uuid', sa.UUID(), nullable=False),
    sa.Column('kitab_title', sa.String(), nullable=True),
    sa.Column('kitab_message', sa.String(), nullable=True),
    sa.Column('kitab_date', sa.String(), nullable=True),
    sa.Column('kitab_size', sa.BigInteger(), nullable=True),
    sa.Column('kitab_link', sa.String(), nullable=True),
    sa.Column('kitab_group', sa.String(), nullable=True),
    sa.Column('maktaba', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maktaba'], ['all_telegram_maktaba_ar.maktaba_id'], ),
    sa.PrimaryKeyConstraint('kitab_id', 'maktaba'),
    sa.UniqueConstraint('kitab_id', 'kitab_link', name='uq_ar_kitab_id_link'),
    sa.UniqueConstraint('kitab_uuid')
    )
    op.create_table('all_telegram_kotob_fr',
    sa.Column('kitab_id', sa.BigInteger(), nullable=False),
    sa.Column('kitab_uuid', sa.UUID(), nullable=False),
    sa.Column('kitab_title', sa.String(), nullable=True),
    sa.Column('kitab_message', sa.String(), nullable=True),
    sa.Column('kitab_date', sa.String(), nullable=True),
    sa.Column('kitab_size', sa.BigInteger(), nullable=True),
    sa.Column('kitab_link', sa.String(), nullable=True),
    sa.Column('kitab_group', sa.String(), nullable=True),
    sa.Column('maktaba', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maktaba'], ['all_telegram_maktaba_fr.maktaba_id'], ),
    sa.PrimaryKeyConstraint('kitab_id', 'maktaba'),
    sa.UniqueConstraint('kitab_id', 'kitab_link', name='uq_kitab_id_link'),
    sa.UniqueConstraint('kitab_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_telegram_kotob_fr')
    op.drop_table('all_telegram_kotob_ar')
    op.drop_table('all_telegram_maktaba_fr')
    op.drop_table('all_telegram_maktaba_ar')
    # ### end Alembic commands ###
