"""fix autu primary key kotob

Revision ID: 5de8f33cadc7
Revises: b138c0c1a5bc
Create Date: 2026-03-13 15:31:33.977613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de8f33cadc7'
down_revision: Union[str, Sequence[str], None] = 'b138c0c1a5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
