"""Update Telegram Tables

Revision ID: 7325ca125032
Revises: 37cc54733b8a
Create Date: 2026-03-12 15:18:09.069873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7325ca125032'
down_revision: Union[str, Sequence[str], None] = '37cc54733b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('all_telegram_kotob_ar_kitab_uuid_key'), 'all_telegram_kotob_ar', type_='unique')
    op.drop_column('all_telegram_kotob_ar', 'kitab_uuid')
    op.drop_constraint(op.f('all_telegram_kotob_fr_kitab_uuid_key'), 'all_telegram_kotob_fr', type_='unique')
    op.drop_column('all_telegram_kotob_fr', 'kitab_uuid')
    op.drop_constraint(op.f('all_telegram_maktaba_ar_maktaba_uuid_key'), 'all_telegram_maktaba_ar', type_='unique')
    op.drop_column('all_telegram_maktaba_ar', 'maktaba_uuid')
    op.drop_constraint(op.f('all_telegram_maktaba_fr_maktaba_uuid_key'), 'all_telegram_maktaba_fr', type_='unique')
    op.drop_column('all_telegram_maktaba_fr', 'maktaba_uuid')
    op.drop_column('all_telegram_maktaba_fr', 'maktaba_id;maktaba_name;maktaba_link;maktaba_info;maktaba_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_telegram_maktaba_fr', sa.Column('maktaba_id;maktaba_name;maktaba_link;maktaba_info;maktaba_at', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('all_telegram_maktaba_fr', sa.Column('maktaba_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('all_telegram_maktaba_fr_maktaba_uuid_key'), 'all_telegram_maktaba_fr', ['maktaba_uuid'], postgresql_nulls_not_distinct=False)
    op.add_column('all_telegram_maktaba_ar', sa.Column('maktaba_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('all_telegram_maktaba_ar_maktaba_uuid_key'), 'all_telegram_maktaba_ar', ['maktaba_uuid'], postgresql_nulls_not_distinct=False)
    op.add_column('all_telegram_kotob_fr', sa.Column('kitab_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('all_telegram_kotob_fr_kitab_uuid_key'), 'all_telegram_kotob_fr', ['kitab_uuid'], postgresql_nulls_not_distinct=False)
    op.add_column('all_telegram_kotob_ar', sa.Column('kitab_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('all_telegram_kotob_ar_kitab_uuid_key'), 'all_telegram_kotob_ar', ['kitab_uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
