"""fixer tout

Revision ID: 84cf60e87a54
Revises: 5de8f33cadc7
Create Date: 2026-03-14 13:43:43.467238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cf60e87a54'
down_revision: Union[str, Sequence[str], None] = '5de8f33cadc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('all_telegram_kotob_fr', 'kitab_title',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('all_telegram_kotob_fr', 'kitab_message',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_date',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_link',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_group',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_link',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_info',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_at',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('all_telegram_maktaba_fr_maktaba_link_key'), 'all_telegram_maktaba_fr', type_='unique')
    op.create_unique_constraint('all_telegram_maktaba_fr_link_key', 'all_telegram_maktaba_fr', ['maktaba_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('all_telegram_maktaba_fr_link_key', 'all_telegram_maktaba_fr', type_='unique')
    op.create_unique_constraint(op.f('all_telegram_maktaba_fr_maktaba_link_key'), 'all_telegram_maktaba_fr', ['maktaba_link'], postgresql_nulls_not_distinct=False)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_at',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_info',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('all_telegram_maktaba_fr', 'maktaba_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('all_telegram_kotob_fr', 'kitab_group',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_link',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_date',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_message',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('all_telegram_kotob_fr', 'kitab_title',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
