"""Update2 Telegram Tables

Revision ID: 8d3b0f90dac4
Revises: 7325ca125032
Create Date: 2026-03-12 15:39:45.088243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3b0f90dac4'
down_revision: Union[str, Sequence[str], None] = '7325ca125032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_kitab_id_link'), 'all_telegram_kotob_fr', type_='unique')
    op.drop_constraint(op.f('all_telegram_kotob_fr_maktaba_fkey'), 'all_telegram_kotob_fr', type_='foreignkey')
    op.create_foreign_key(None, 'all_telegram_kotob_fr', 'all_telegram_maktaba_fr', ['maktaba'], ['maktaba_id'], initially='DEFERRED', deferrable=True)
    op.drop_column('all_telegram_kotob_fr', 'maktaba;kitab_id;kitab_title;kitab_message;kitab_date;kitab_siz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_telegram_kotob_fr', sa.Column('maktaba;kitab_id;kitab_title;kitab_message;kitab_date;kitab_siz', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'all_telegram_kotob_fr', type_='foreignkey')
    op.create_foreign_key(op.f('all_telegram_kotob_fr_maktaba_fkey'), 'all_telegram_kotob_fr', 'all_telegram_maktaba_fr', ['maktaba'], ['maktaba_id'])
    op.create_unique_constraint(op.f('uq_kitab_id_link'), 'all_telegram_kotob_fr', ['kitab_id', 'kitab_link'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
