"""fix primary key kotob

Revision ID: b138c0c1a5bc
Revises: 8d3b0f90dac4
Create Date: 2026-03-13 15:11:33.776134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b138c0c1a5bc'
down_revision: Union[str, Sequence[str], None] = '8d3b0f90dac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
